/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivitiesRouteImport } from './routes/activities'
import { Route as MembersRouteImport } from './routes/members'
import { Route as PeerMentorRouteImport } from './routes/peer-mentor'
import { Route as WhatIsSwagRouteImport } from './routes/what-is-swag'
import { Route as FormIndexRouteImport } from './routes/form/index'
import { Route as FormBookingRouteImport } from './routes/form/booking'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesRoute = ActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const PeerMentorRoute = PeerMentorRouteImport.update({
  id: '/peer-mentor',
  path: '/peer-mentor',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatIsSwagRoute = WhatIsSwagRouteImport.update({
  id: '/what-is-swag',
  path: '/what-is-swag',
  getParentRoute: () => rootRouteImport,
} as any)
const FormIndexRoute = FormIndexRouteImport.update({
  id: '/form/',
  path: '/form/',
  getParentRoute: () => rootRouteImport,
} as any)
const FormBookingRoute = FormBookingRouteImport.update({
  id: '/form/booking',
  path: '/form/booking',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/members': typeof MembersRoute
  '/peer-mentor': typeof PeerMentorRoute
  '/what-is-swag': typeof WhatIsSwagRoute
  '/form/booking': typeof FormBookingRoute
  '/form/': typeof FormIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/members': typeof MembersRoute
  '/peer-mentor': typeof PeerMentorRoute
  '/what-is-swag': typeof WhatIsSwagRoute
  '/form/booking': typeof FormBookingRoute
  '/form': typeof FormIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/members': typeof MembersRoute
  '/peer-mentor': typeof PeerMentorRoute
  '/what-is-swag': typeof WhatIsSwagRoute
  '/form/booking': typeof FormBookingRoute
  '/form/': typeof FormIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activities'
    | '/members'
    | '/peer-mentor'
    | '/what-is-swag'
    | '/form/booking'
    | '/form/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activities'
    | '/members'
    | '/peer-mentor'
    | '/what-is-swag'
    | '/form/booking'
    | '/form'
  id:
    | '__root__'
    | '/'
    | '/activities'
    | '/members'
    | '/peer-mentor'
    | '/what-is-swag'
    | '/form/booking'
    | '/form/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivitiesRoute: typeof ActivitiesRoute
  MembersRoute: typeof MembersRoute
  PeerMentorRoute: typeof PeerMentorRoute
  WhatIsSwagRoute: typeof WhatIsSwagRoute
  FormBookingRoute: typeof FormBookingRoute
  FormIndexRoute: typeof FormIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities': {
      id: '/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof ActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/peer-mentor': {
      id: '/peer-mentor'
      path: '/peer-mentor'
      fullPath: '/peer-mentor'
      preLoaderRoute: typeof PeerMentorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/what-is-swag': {
      id: '/what-is-swag'
      path: '/what-is-swag'
      fullPath: '/what-is-swag'
      preLoaderRoute: typeof WhatIsSwagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/form/': {
      id: '/form/'
      path: '/form'
      fullPath: '/form/'
      preLoaderRoute: typeof FormIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/form/booking': {
      id: '/form/booking'
      path: '/form/booking'
      fullPath: '/form/booking'
      preLoaderRoute: typeof FormBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivitiesRoute: ActivitiesRoute,
  MembersRoute: MembersRoute,
  PeerMentorRoute: PeerMentorRoute,
  WhatIsSwagRoute: WhatIsSwagRoute,
  FormBookingRoute: FormBookingRoute,
  FormIndexRoute: FormIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
